WebRTC/Pages/Agreement.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace WebRTC.Pages
{
    public class AgreementModel : PageModel
    {
        public void OnGet()
        {
        }
        public IActionResult OnGetAgreeClick()
        {
            HttpContext.Session.SetInt32("Agreement", 1);
            return Redirect("/");
            // code goes here 
        }
        public IActionResult OnGetRejectClick()
        {
            HttpContext.Session.SetInt32("Agreement", 0);
            return Redirect("/");
            // code goes here 
        }
    }
}

WebRTC/Pages/Shared/AgreementModal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    #agreement-modal {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding: 0px;
        position: absolute;
        width: 320px;
        height: 207px;
        left: calc(50% - 330px/2);
        display:none;
        bottom:0px;
    }

    .Grouped{
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding: 10px 0px;
        gap: 8px;
        width: 320px;
        height: 40px;
        background: linear-gradient(0deg, #000000, #000000), linear-gradient(0deg, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.5)), rgba(171, 171, 171, 0.5);
        background-blend-mode: soft-light, normal, luminosity;
        backdrop-filter: blur(45px);
        /* Note: backdrop-filter has minimal browser support */
        border-radius: 12px 12px 0px 0px;
        /* Inside auto layout */
        flex: none;
        order: 0;
        align-self: stretch;
        flex-grow: 0;
    }
    .header{
        width: 320px;
        height: 20px;
        /* Inside auto layout */
        flex: none;
        order: 0;
        align-self: stretch;
        flex-grow: 0;
    }
    .eclipse13{
        position: absolute;
        width: 19px;
        height: 19px;
        left: 12px;
        top: 10px;
        background: #FFFFFF!important;
    }

    .label-app-name{
        
        /* label-app-name */

        position: absolute;
        width: 86px;
        height: 14px;
        left: 32px;
        top: 13px;

        font-family: 'Helvetica';
        font-style: normal;
        font-weight: 400;
        font-size: 12px;
        line-height: 14px;
        color:#FFFFFF;
        /* identical to box height */
        letter-spacing: -0.01em;
    }
    .footer{
        /* Auto layout */
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding: 16px;
        gap: 16px;
        width: 320px;
        height: 167px;
        background: linear-gradient(0deg, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)), linear-gradient(0deg, rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0.3)), rgba(171, 171, 171, 0.5);
        background-blend-mode: soft-light, normal, luminosity;
        backdrop-filter: blur(45px);
        /* Note: backdrop-filter has minimal browser support */
        border-radius: 0px 0px 12px 12px;
        /* Inside auto layout */
        flex: none;
        order: 1;
        align-self: stretch;
        flex-grow: 0;
    }

    .label-content{
        width: 288px;
        height: 75px;
        font-family: 'Helvetica';
        font-style: normal;
        font-weight: 400;
        font-size: 12px;
        line-height: 15px;
        /* or 125% */
        letter-spacing: -0.01em;
        /* Inside auto layout */
        flex: none;
        order: 0;
        align-self: stretch;
        flex-grow: 0;
        color:#FFFFFF
    }
    .buttons{
        width: 288px;
        height: 44px;
        /* Inside auto layout */
        flex: none;
        order: 1;
        align-self: stretch;
        flex-grow: 0;
    }

    .keep{
        position: absolute;
        height: 44px;
        left: 13px;
        right: 152px;
        bottom: 20px;

        background: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), linear-gradient(0deg, rgba(255, 255, 255, 0.4), rgba(255, 255, 255, 0.4)), rgba(255, 255, 255, 0.4);
        background-blend-mode: soft-light, normal, luminosity;
        backdrop-filter: blur(45px);
        /* Note: backdrop-filter has minimal browser support */
        border-radius: 8px;
         width:140px;
    }
    .keep-label{
            position: absolute;
            width: 46px;
            height: 17px;
            left: calc(50% - 46px/2);
            top: calc(50% - 17px/2 - 0.5px);
            font-family: 'Helvetica';
            font-style: normal;
            font-weight: 400;
            font-size: 15px;
            line-height: 17px;
            text-align: center;
            letter-spacing: -0.01em;
            color: #9747FF;
    }

    .turn-off{
        position: absolute;
        height: 44px;
        right: 13px;
        bottom: 20px;
        background: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), linear-gradient(0deg, rgba(255, 255, 255, 0.4), rgba(255, 255, 255, 0.4)), rgba(255, 255, 255, 0.4);
        background-blend-mode: soft-light, normal, luminosity;
        backdrop-filter: blur(45px);
        /* Note: backdrop-filter has minimal browser support */
        border-radius: 8px;
        width:140px;
    }
    .turn-off-label{
        position: absolute;
        width: 42px;
        height: 17px;
        left: calc(50% - 42px/2);
        top: calc(50% - 17px/2 - 0.5px);

        font-family: 'Helvetica';
        font-style: normal;
        font-weight: 400;
        font-size: 15px;
        line-height: 17px;
        text-align: center;
        letter-spacing: -0.01em;

        color: #9747FF;
    }
</style>

<div id="agreement-modal">
    <div class="Grouped">
        <div class="header">
            <div class="eclipse13 rounded-circle">

            </div>
            <label class="label-app-name">
                UR Agreement
            </label>
        </div>
    </div>
    <div class="footer">

        <label class="label-content">
            All calls made through our platform are encrypted end-to-end, ensuring the highest level of privacy for your conversations.

            By clicking Accept, you confirm that you are over 18 and verify that you are a human, not a bot or automated system.
        </label>
@*        <div class="buttons">
            <a class="keep" style="border:none!important" asp-page="Agreement" asp-page-handler="AgreeClick">
                <span class="keep-label">
                    Accept
                </span>
            </a>
            <a class="turn-off" style="border:none!important" asp-page="Agreement" asp-page-handler="RejectClick">
                <span class="turn-off-label">
                    Reject
                </span>
            </a>
        </div>*@
        <div class="buttons">
            <button class="keep" id="acceptBtn" style="border:none!important">
                <span class="keep-label">
                    Accept
                </span>
            </button>
            <button class="turn-off" id="rejectBtn" style="border:none!important">
                <span class="turn-off-label">
                    Reject
                </span>
            </button>
        </div>
    </div>
</div>

WebRTC/Pages/Shared/ErrorHandlingModal.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<style>
    #error-modal {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding: 0px;
        position: absolute;
        width: 320px;
        height: 207px;
        left: calc(50% - 320px/2);
        display: none;
        bottom: 0px;
    }

    .Grouped {
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding: 10px 0px;
        gap: 8px;
        width: 320px;
        height: 40px;
        background: linear-gradient(0deg, #000000, #000000), linear-gradient(0deg, rgba(255, 255, 255, 0.5), rgba(255, 255, 255, 0.5)), rgba(171, 171, 171, 0.5);
        background-blend-mode: soft-light, normal, luminosity;
        backdrop-filter: blur(45px);
        /* Note: backdrop-filter has minimal browser support */
        border-radius: 12px 12px 0px 0px;
        /* Inside auto layout */
        flex: none;
        order: 0;
        align-self: stretch;
        flex-grow: 0;
    }

    .header {
        width: 320px;
        height: 20px;
        /* Inside auto layout */
        flex: none;
        order: 0;
        align-self: stretch;
        flex-grow: 0;
    }

    .eclipse13 {
        position: absolute;
        width: 19px;
        height: 19px;
        left: 12px;
        top: 10px;
        background:transparent;
    }

    .error-label-app-name {
        /* label-app-name */

        position: absolute;
        width: 100%;
        height: 14px;
        left: 32px;
        top: 13px;
        font-family: 'Helvetica';
        font-style: normal;
        font-weight: 400;
        font-size: 12px;
        line-height: 14px;
        color: #FFFFFF;
        /* identical to box height */
        letter-spacing: -0.01em;
    }

    .footer {
        /* Auto layout */
        display: flex;
        flex-direction: column;
        align-items: flex-start;
        padding: 16px;
        gap: 16px;
        width: 320px;
        height: 167px;
        background: linear-gradient(0deg, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.8)), linear-gradient(0deg, rgba(255, 255, 255, 0.3), rgba(255, 255, 255, 0.3)), rgba(171, 171, 171, 0.5);
        background-blend-mode: soft-light, normal, luminosity;
        backdrop-filter: blur(45px);
        /* Note: backdrop-filter has minimal browser support */
        border-radius: 0px 0px 12px 12px;
        /* Inside auto layout */
        flex: none;
        order: 1;
        align-self: stretch;
        flex-grow: 0;
    }

    .label-content {
        width: 288px;
        height: 75px;
        font-family: 'Helvetica';
        font-style: normal;
        font-weight: 400;
        font-size: 12px;
        line-height: 15px;
        /* or 125% */
        letter-spacing: -0.01em;
        /* Inside auto layout */
        flex: none;
        order: 0;
        align-self: stretch;
        flex-grow: 0;
        color: #FFFFFF
    }

    .buttons {
        width: 288px;
        height: 44px;
        /* Inside auto layout */
        flex: none;
        order: 1;
        align-self: stretch;
        flex-grow: 0;
    }

    .keep {
        position: absolute;
        height: 44px;
        left: 13px;
        right: 152px;
        bottom: 20px;
        background: linear-gradient(0deg, rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.4)), linear-gradient(0deg, rgba(255, 255, 255, 0.4), rgba(255, 255, 255, 0.4)), rgba(255, 255, 255, 0.4);
        background-blend-mode: soft-light, normal, luminosity;
        backdrop-filter: blur(45px);
        /* Note: backdrop-filter has minimal browser support */
        border-radius: 8px;
        width: 140px;
    }

    .keep-label {
        position: absolute;
        width: 46px;
        height: 17px;
        left: calc(50% - 46px/2);
        top: calc(50% - 17px/2 - 0.5px);
        font-family: 'Helvetica';
        font-style: normal;
        font-weight: 400;
        font-size: 15px;
        line-height: 17px;
        text-align: center;
        letter-spacing: -0.01em;
        color: #9747FF;
    }

    .Errturn-off {
        position: absolute;
        height: 44px;
        right: 13px;
        bottom: 40px;
        width: 140px;
        background-color:transparent!important
    }

    .Errturn-off-label {
        position: absolute;
        width: 42px;
        height: 17px;
        left: calc(50% - 42px/2);
        top: calc(50% - 17px/2 - 0.5px);
        font-family: 'Helvetica';
        font-style: normal;
        font-weight: 400;
        font-size: 15px;
        line-height: 17px;
        text-align: center;
        letter-spacing: -0.01em;
        color: #9747FF;
        background-color:transparent!important
    }
</style>
<div class="errorModalDiv hidden">
</div>
<div id="error-modal">
    <div class="Grouped">
        <div class="header">
            <div class="eclipse13 rounded-circle">
            </div>
            <label class="error-label-app-name">
                OPS something goes wrong 
            </label>
        </div>
    </div>
    <div class="footer">

        <label class="label-content">
        </label>
    </div>
    <div class="buttons">
            <button class="keep" id="okBtn" style="border:none!important" onclick="closeErrorModal()">
            <span class="keep-label">
                Ok
            </span>
        </button>
@*        <div class="Errturn-off" id="rejectBtn" style="border:none!important">
            <span class="Errturn-off-label">
                <img src="~/img/badsmile.png" style="width:40px;height:40px;position:absolute;left:0px;top:10px" />
            </span>
        </div>*@

    </div>
</div>

WebRTC/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en" style="height:100%;width:100%">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebRTC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebRTC.styles.css" asp-append-version="true" />
    <link href="~/lib/font-awesome/css/all.css" rel="stylesheet" />
    <link href="~/lib/font-awesome/css/all.min.css" rel="stylesheet" />
    <link href="~/lib/alertifyjs/build/css/alertify.min.css" rel="stylesheet" />
    <link href="~/css/sidebar.css" rel="stylesheet" />

    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/signalr/dist/browser/signalr.min.js"></script>
    <script src="~/lib/jquery/jquery.js"></script>
    <style>
        body{
/*            background: linear-gradient(180deg, #E100E5 0%, #16CFFF 100%);
            background-repeat:no-repeat;*/
            margin: 0!important;
            padding: 0!important;
            width: 100%;
            height: 100%;
            min-height: 100%;
            background: linear-gradient(180deg, #39C4FF 1.6%, #F81EE2 100%);
            background-repeat: no-repeat;
            background-attachment: fixed;
        }
    </style>
</head>
<body style="height:100%;width:100%;" class="toggled">
@*    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">WebRTC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>*@
    <div class="toggleBtn text-white text-xxl-center">
        <span class="fa fa-bars text-white text-xxl-center"></span>
    </div>
    <div class="sidebar" style="display:none">
        <div class="row" style="height:15%">
            <div class="col-sm-12 text-center" >
                <div class="row no-gutters" style="width:200px;height:100%;margin-left:auto!important;margin-right:auto!important;box-sizing:border-box;position:relative">
                    <div class="openBtn">

                    </div>
@*                    <div class="closeBtn" style="cursor:pointer; width:30%;height:100%!important;background-image:url(/img/close.png);background-size:contain;background-repeat:no-repeat;background-position:center;border:18px solid transparent;border-top:25px solid transparent!important;box-sizing:border-box">

                    </div>*@
                    <div class="closeBtn">
                        <span class="fa fa-arrow-right text-white" style="font-size:x-large!important;position:absolute;top:43%"></span>
                    </div>
                </div>
            </div>
        </div>
@*        <div class="" style="width:100%;height:15%;">
            <div style="width:200px;height:120px;margin-left:auto;margin-right:auto;position:relative;" class="p-2">
                <img src="~/img/logowhite.png" class="sidebar-head" />
                <div class="closeButtonDiv">
                    <span class="sidebar-close d-inline-block"><span class="line1"></span><span class="line2"></span></span>
                </div>
            </div>
        </div>*@
        <div class="text-center ulDiv">
            <div style="width:100%;height:300px;display:inline-block;padding-top:70px;">
                <ul style="display: inline-block;text-align: left;">
@*                    <li class="text" style="margin-left:-55px;"><a href="/Society" style="color:#FFFFFF!important;text-decoration:none!important;position:relative;left:0px">Our Society</a></li>*@
                    <li class="text" style="margin-left:-55px;"><a href="/Pledge" style="color:#FFFFFF!important;text-decoration:none!important;position:relative;left:0px">Our Pledge</a></li>
                    <li class="text" style="margin-left:-55px;"><a href="/Contact" style="color:#FFFFFF!important;text-decoration:none!important;position:relative;left:0px">Our Contact</a></li>
                </ul>
            </div>
        </div>
        <div class="text-center" style="width:100%;height:15%;position:relative;">
            <img src="~/img/Line 2.png" style="height:5px!important;" />
            <div class="row">
                <div class="col-12">
                    <a class="d-inline-block" style="cursor:pointer">
                        <img src="~/img/facebook.png" class="d-inline-block" />
                    </a>&nbsp;&nbsp;
                    <a class="d-inline-block" style="cursor:pointer">
                        <img src="~/img/instagram.png" class="d-inline-block" />
                    </a>
                </div>
            </div>
        </div>
@*        <div class="row text-center pt-5" style="height:20%;width:100%">
            <h1 class=""><p class="sidebar-head d-inline-block">Society</p> <span class="sidebar-close d-inline-block"><span class="line1"></span><span class="line2"></span></span></h1>
        </div>*@
@*        <div class="row" style="height:20%;width:100%;">
            <div class="col-sm-12">
                <div style="width:176px;height:89px;display:block;margin-left:auto;margin-right:auto;background-image:url(/img/logowhite.png)"></div>
            </div>
        </div>*@
@*        <div class="row text-center" style="height:60%;width:100%;padding-top:100px;text-align: center;">
            <div class="col-sm-4"></div>
            <div class="col-sm-8 text-start">
                <ul class="myUL" style="display: inline-block;text-align: left;">
                    <li class="text"><a href="/Society" style="color:#FFFFFF!important;text-decoration:none!important;position:relative;left:30px">Our Society</a></li>
                    <li class="text"><a href="/Pledge" style="color:#FFFFFF!important;text-decoration:none!important;position:relative;left:30px">Our Pledge</a></li>
                    <li class="text"><a href="/Contact" style="color:#FFFFFF!important;text-decoration:none!important;position:relative;left:30px">Our Contact</a></li>
                </ul>
            </div>
        </div>
        <div class="row text-center" style="height:20%;width:100%;position:relative">
            <img src="~/img/Line 2.png" style="height:5px!important" />
            <div class="row">
                <div class="col-12"><a class="d-inline-block"><img src="~/img/facebook.png" class="d-inline-block" /></a>&nbsp;&nbsp;<a class="d-inline-block"><img src="~/img/instagram.png" class="d-inline-block" /></a></div>
            </div>
        </div>*@
    </div>
    <div class="container" style="height:100%;width:100%">
        <main role="main" id="main" class="pb-3" style="height:100%;width:100%;;">
            @RenderBody()
        </main>
    </div>

@*    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebRTC - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>*@

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/font-awesome/js/all.js"></script>
    <script src="~/lib/font-awesome/js/all.min.js"></script>
    <script src="~/lib/alertifyjs/build/alertify.min.js"></script>
    <script src="~/js/utilsRTC.js"></script>
    <script src="~/js/constWebRTC.js"></script>
    <script src="~/lib/adapterjs/adapter.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script type="text/javascript">
        $(".toggleBtn").click(function () {
            $(".sidebar").animate({
                width: "toggle"
            });
            $("#main").addClass('blured');
        });
        $("#openMenu").click(function () {
            $(".sidebar").animate({
                width: "toggle"
            });
            $("#main").addClass('blured');
        });
        $(".openBtn").click(function () {
            window.location.href="/";
        });
        //$(".sidebar-close").click(function () {
        //    $(".sidebar").animate({
        //        width: "toggle"
        //    });
        //    $("#main").removeClass('blured');
        //});
        $(".closeBtn").click(function () {
            $(".sidebar").animate({
                width: "toggle"
            });
            $("#main").removeClass('blured');
        });

        $(".sidebar-head").click(function(){
            window.location.href="/";
        })

    </script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>